"""add password hash

Revision ID: 5219d627b917
Revises: b969956c2acf
Create Date: 2025-08-31 19:02:49.769716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5219d627b917'
down_revision: Union[str, Sequence[str], None] = 'b969956c2acf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'books', ['uid'])
    op.create_unique_constraint(None, 'user_accounts', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_accounts', type_='unique')
    op.drop_constraint(None, 'books', type_='unique')
    # ### end Alembic commands ###
